### ISSUE TITLE
PDO DiedSQLSTATE[42S22]: Column not found: 1054 Unknown column 'pid' in 'where clause'

### ISSUE THREAD

**Issue by zzzshanghai** [NeToucher/WHMCS_Shadowsocks_Module#6]
whmcs version 6.3.1

PDO DiedSQLSTATE[42S22]: Column not found: 1054 Unknown column 'pid' in 'where clause'

Could you please give me some advise? Thank you.

**Comment by gaukas** [comment]
```
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(32) NOT NULL,
  `pass` varchar(32) NOT NULL,
  `passwd` varchar(32) NOT NULL,
  `t` int(11) NOT NULL DEFAULT '0',
  `u` bigint(20) NOT NULL,
  `d` bigint(20) NOT NULL,
  `transfer_enable` bigint(20) NOT NULL,
  `port` int(11) NOT NULL,
  `switch` tinyint(4) NOT NULL DEFAULT '1',
  `enable` tinyint(4) NOT NULL DEFAULT '1',
  `type` tinyint(4) NOT NULL DEFAULT '1',
  `last_get_gift_time` int(11) NOT NULL DEFAULT '0',
  `last_rest_pass_time` int(11) NOT NULL DEFAULT '0',
  `pid` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Please refer to the database structure above. That's the version we are using for debugging & developing purposes. 
Thank you for notifying us this problem. We have also corrected the SQL file in the archive repository [https://github.com/NeToucher/shadowsocks-rm/blob/manyuser/shadowsocks/shadowsocks.sql](https://github.com/NeToucher/shadowsocks-rm/blob/manyuser/shadowsocks/shadowsocks.sql)

**Comment by zzzshanghai** [comment]
Hi,

I try to input https://github.com/NeToucher/shadowsocks-rm/blob/manyuser/shadowsocks/shadowsocks.sql through phpmyadmin

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES ('0', 'test@test.com', '123456', '0000000', '1410609560', '0', '0', '9320666234', '50000', '1', '1', '7', '0', '0')


#1136 - Column count doesn't match value count at row 1

**Comment by zzzshanghai** [comment]
I try to input the database structure you mentioned above through phpmyadmin

#1075 - Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by gaukas** [comment]
Hello there,
We have corrected the SQL file just now. Please try again.

**Comment by gaukas** [comment]
```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `email` varchar(32) NOT NULL,
  `pass` varchar(32) NOT NULL,
  `passwd` varchar(32) NOT NULL,
  `t` int(11) NOT NULL DEFAULT 0,
  `u` bigint(20) NOT NULL,
  `d` bigint(20) NOT NULL,
  `transfer_enable` bigint(20) NOT NULL,
  `port` int(11) NOT NULL,
  `switch` tinyint(4) NOT NULL DEFAULT 1,
  `enable` tinyint(4) NOT NULL DEFAULT 1,
  `type` tinyint(4) NOT NULL DEFAULT 1,
  `last_get_gift_time` int(11) NOT NULL DEFAULT 0,
  `last_rest_pass_time` int(11) NOT NULL DEFAULT 0,
  `pid` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `user` (`id`, `email`, `pass`, `passwd`, `t`, `u`, `d`, `transfer_enable`, `port`, `switch`, `enable`, `type`, `last_get_gift_time`, `last_rest_pass_time`, `pid`) VALUES
(0, '', '', '0000000', 0, 0, 0, 1, 8000, 1, 1, 1, 0, 0, 0);


ALTER TABLE `user`
  ADD PRIMARY KEY (`id`,`port`),
  ADD UNIQUE KEY `pid` (`pid`);


ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

```
For your information.

**Comment by zzzshanghai** [comment]
Hi,

Everything is OK. Thank you very much. 

Can you speak Chinese?

**Comment by zzzshanghai** [comment]
I can use "Configurable Options" in the 1.0.0 whmcs-shadowsocks (by Tension). And I can set "traffic|month" for 1|1GB ; 2|2GB etc. Can I use this in version 3.0? Thank you.

**Comment by gaukas** [comment]
Hello,
I think my Chinese is poor.
The traffic pack is still available. This is a imcomplete project as I don’t have enough time to write a document for it :P. In Configurable Options, you need to create a Option named ‘Traffic’ and set your options to start with the amount of traffic per month and followed by letter ‘G’. For example,  if a customer choose the option called ‘10G-Basic’, this module automatically use ‘10’, as the number before the first ‘G’ letter, to set monthly traffic for this user.

**Comment by zzzshanghai** [comment]
Hi,
Is it the same in 1.0.0 whmcs-shadowsocks (by Tension)? I try to use Configurable Options, but failed. Could you give me some advice? Thank you.

Option Name:  traffic|traffic/month
Option Type: Radio

Options: 1|1GB/month
               2|2GB/month
               3|3GB/month

**Comment by gaukas** [comment]
They are different from each other. Changed from ‘{traffic}|{customized text}’ to ‘{traffic}G{customized text}’.

**Comment by zzzshanghai** [comment]
Hi,
I use  ‘{traffic}G{customized text}’ you mentioned above, but failed.

Option Name: trafficG/month
Option Type: Radio
Options: 1G/month
 2G/month
 3G/month

**Comment by gaukas** [comment]
Please note that:
Option Name should be 'Traffic' and Options should be in the format as ‘{traffic}|{customized text}’.

**Comment by gaukas** [comment]
![image](https://user-images.githubusercontent.com/9084527/36592864-64f6f932-188f-11e8-8df6-9d3741d7a2f8.png)
Please find the image as a reference.

**Comment by zzzshanghai** [comment]
Hi，
I use the image as a reference. It's OK now. Thank you.

In version 1.0 (by tension),  when I choose "20G" and press "save" button, the traffic will change from 10G to 20G, etc.

But in this version, I have to choose "terminate", then choose "20G" and press "save" button,  then press "create", and the traffic will change from 10G to 20G.

**Comment by gaukas** [comment]
Yes. This feature is added to support the monthly traffic reset/add features, which are not included in tension's version. If you need that feature, please feel free to clone this project to local and make any changes you want.

**Comment by zzzshanghai** [comment]
Hi,
WHCMS configration is OK.
I use git clone -b manyuser https://github.com/NeToucher/shadowsocks-rm.git ssadmin
I put a config.json into /root/ssadmin/shadowsocks
{
    "server":"0.0.0.0",
    "server_ipv6": "[::]",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"m",
    "timeout":300,
    "method":"aes-256-cfb"
}
And I set the MySQL database in config.py

I try to use python server.py and the service is UP.
But when use  netstat -tunlp | grep python

tcp        0      0 0.0.0.0:8388                0.0.0.0:*                   LISTEN      4255/python
udp        0      0 0.0.0.0:8388                0.0.0.0:*                               4255/python

It means shadowsock can not read the data from MySQL database. Could you please give me some advice? Thank you.

**Comment by gaukas** [comment]
Please check if your MySQL user could be logged in from your shadowsocks server first. Then you may check out if your MySQL server can be reached. 

Fyi, if you are about to starting up your business of shadowsocks access, you may wish to cooperate with us in order to avoid the potential business conflict between you and an organization under NETOUCHER LIMITED. If you are interested in further cooperation, please reply me. I will send you an invitation link to our Telegram group.

**Comment by zzzshanghai** [comment]
In mainland China, it is illegal to sell shadowsocks. I sell shared web-hosting and domains serveral years ago. I have a WHMCS lifetime version. I am intereted in learning linux, php, mysql, whmcs, etc. Thank you for your help. Happy Chinese new year.

**Comment by gaukas** [comment]
Good luck! I wish you success!
